### PR TITLE
add attributes transform like React

### PR DESCRIPTION
**Pull request by Ehres**
This PR is for use all attributes like react: 'onClick', 'autoPlay', ...
You can look all attributes in son files.

### CODE REVIEW

**Comment by alecsgone** [comment]
hey @Ehres thanks for the contribution, I'll take a look later today

**Comment by Ehres** [comment]
Hi, yesterday I look and resolved conflicts. Have you any time to check this PR ?

**Comment by alecsgone** [comment]
I did but what we are trying to do is to keep the lib really small and this PR increases the weight a lot with the events that we currently use by calling the ref, and also the description of every tag is very large.
I was thinking if this can be some sort of plugin, @sebasrgl any ideas?

```jsx
const actions = {
  clickHandler: el => {
    el.addEventListener('event', cb)
  }
}

function foo () {
  return (
    <button ref={actions.clickHandler} > click </button>
  )
}

**Comment by alecsgone** [comment]
Is true, will be very simple, so I'll try to think on a plugin way to do it on the mean time I can tell you is definitelly a **no** for the `src/HTML_TAGS.json` file, because tests are exactly the same with or without that file, the audioTagTest passes equally in master

```js
test('Component render AUDIO tags', t => {
  function renderAudioSingleTag() {
    return (
      <audio autoPlay autoBuffer src="foo.mp3" />
    )
  }

  function renderMultipleAudioSRC() {
    return (
      <audio controls="controls">
        <source src="horse.ogg" type="audio/ogg" />
        <source src="horse.mp3" type="audio/mpeg" />
        Your browser does not support the audio element.
      </audio>
    )
  }

  t.is(renderAudioSingleTag().outerHTML, '<audio autoplay="true" autobuffer="true" src="foo.mp3"></audio>',
    'Single audio tag Renders Correctly')

  t.is(renderMultipleAudioSRC().outerHTML, '<audio controls="controls"><source src="horse.ogg" type="audio/ogg"><source src="horse.mp3" type="audio/mpeg">Your browser does not support the audio element.</audio>',
    'Multi SRC audio tag Renders Correctly')
})
```

on the other hand about the GLOBAL_ATTRIBUTES I can't see a test that reflects how it benefits the lib, so initially is **no** but I'll dig into those global attrs later.

**Comment by alecsgone** [comment]
```js
import dom, { Fragment } from  'jsx-render'
import EventTag from 'jsx-render/lib/eventAttrs'

const MyButton = props => EventTag(<button onClick={cb} {...props}>click</button>)

function MyBox () {
  return (
   ...
    <MyButton />
   ...
  )
}

```
or
```jsx
import EventTag from 'jsx-render/lib/eventAttrs'

const MyButton = props => (
  <EventTag>
    <button onClick={cb} {...props}>click</button>
  </EventTag>
)

const MyBox = () => (
 ...
  <MyButton />
 ...
)
```
how do you feel about this initial blueprints ?

**Comment by Ehres** [comment]
Ok thanks for your returns. This last proposal is, for me and my job, too different to react. I'm ok for HTML_TAGS and GLOBAL_ATTRIBUTES but I need EVENT_HANDLERS. I think what I keep my fork and publish on private registry and maintain it.

**Pull request closed without merging**
